/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeporteSportRouteImport } from './routes/deporte.$sport'
import { Route as EquipoSlugRouteImport } from './routes/equipo.$slug'
import { Route as PartidoIdRouteImport } from './routes/partido.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeporteSportRoute = DeporteSportRouteImport.update({
  id: '/deporte/$sport',
  path: '/deporte/$sport',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoSlugRoute = EquipoSlugRouteImport.update({
  id: '/equipo/$slug',
  path: '/equipo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidoIdRoute = PartidoIdRouteImport.update({
  id: '/partido/$id',
  path: '/partido/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deporte/$sport': typeof DeporteSportRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/partido/$id': typeof PartidoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deporte/$sport': typeof DeporteSportRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/partido/$id': typeof PartidoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deporte/$sport': typeof DeporteSportRoute
  '/equipo/$slug': typeof EquipoSlugRoute
  '/partido/$id': typeof PartidoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deporte/$sport' | '/equipo/$slug' | '/partido/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deporte/$sport' | '/equipo/$slug' | '/partido/$id'
  id: '__root__' | '/' | '/deporte/$sport' | '/equipo/$slug' | '/partido/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeporteSportRoute: typeof DeporteSportRoute
  EquipoSlugRoute: typeof EquipoSlugRoute
  PartidoIdRoute: typeof PartidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deporte/$sport': {
      id: '/deporte/$sport'
      path: '/deporte/$sport'
      fullPath: '/deporte/$sport'
      preLoaderRoute: typeof DeporteSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/$slug': {
      id: '/equipo/$slug'
      path: '/equipo/$slug'
      fullPath: '/equipo/$slug'
      preLoaderRoute: typeof EquipoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partido/$id': {
      id: '/partido/$id'
      path: '/partido/$id'
      fullPath: '/partido/$id'
      preLoaderRoute: typeof PartidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeporteSportRoute: DeporteSportRoute,
  EquipoSlugRoute: EquipoSlugRoute,
  PartidoIdRoute: PartidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
